## Deliverable 3. Create a Travel Itinerary Map.

In [3]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [10]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()

City_ID          City Country  Max Temp Current Description      Lat  \
0        2         Kapaa      US     80.58          few clouds  22.0752   
1        6          Poum      NC     78.33     overcast clouds -20.2333   
2        7    Mahibadhoo      MV     81.70     overcast clouds   3.7833   
3       10  Quatre Cocos      MU     79.09           clear sky -20.2078   
4       15       Isangel      VU     81.72     overcast clouds -19.5500   

        Lng                           Hotel Name  
0 -159.3190  Sheraton Kauai Coconut Beach Resort  
1  164.0167                          Gîte kajeon  
2   72.9667                          Omadhoo Inn  
3   57.7625               Sunrise Attitude Hotel  
4  169.2667                          Tanna Lodge

In [12]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]


# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [13]:
# 4a. Add a marker layer for each city to the map.
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
# 4b. Display the figure
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.4)
fig.add_layer(marker_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [27]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[vacation_df['City'] == 'Sibolga']
vacation_end = vacation_df.loc[vacation_df['City'] == 'Sibolga']
vacation_stop1 = vacation_df.loc[vacation_df['City'] == 'Padang']
vacation_stop2 = vacation_df.loc[vacation_df['City'] == 'Pringsewu'] 
vacation_stop3 = vacation_df.loc[vacation_df['City'] == 'Kawalu'] 



In [26]:
vacation_start

City_ID     City Country  Max Temp Current Description     Lat      Lng  \
107      455  Sibolga      ID     85.06     overcast clouds  1.7427  98.7792   

                      Hotel Name  
107  Hotel Syariah CN Darussalam

In [25]:
vacation_stop1

City_ID    City Country  Max Temp Current Description     Lat       Lng  \
40      172  Padang      ID     86.05     overcast clouds -0.9492  100.3543   

        Hotel Name  
40  Mercure Padang

In [30]:
vacation_stop2

City_ID       City Country  Max Temp Current Description     Lat  \
134      574  Pringsewu      ID     84.96     overcast clouds -5.3582   

          Lng                Hotel Name  
134  104.9744  Urban Style by Front One

In [31]:
vacation_stop3

City_ID    City Country  Max Temp Current Description     Lat       Lng  \
139      585  Kawalu      ID     81.14       broken clouds -7.3817  108.2082   

           Hotel Name  
139  KOSAN UNGU UNSIK

In [32]:
vacation_end

City_ID     City Country  Max Temp Current Description     Lat      Lng  \
107      455  Sibolga      ID     85.06     overcast clouds  1.7427  98.7792   

                      Hotel Name  
107  Hotel Syariah CN Darussalam

In [34]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start.iloc[0,5:7].to_numpy()
end = vacation_end.iloc[0,5:7].to_numpy()
stop1 = vacation_stop1.iloc[0,5:7].to_numpy()
stop2 = vacation_stop2.iloc[0,5:7].to_numpy()
stop3 = vacation_stop3.iloc[0,5:7].to_numpy()
start

array([1.7427, 98.7792], dtype=object)

In [35]:
stop1

array([-0.9492, 100.3543], dtype=object)

In [36]:
stop2

array([-5.3582, 104.9744], dtype=object)

In [37]:
stop3

array([-7.3817, 108.2082], dtype=object)

In [38]:
end

array([1.7427, 98.7792], dtype=object)

In [39]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig = gmaps.figure(center=(38, -122), zoom_level = 7)
Sibolga = start
Padang = stop1
Pringsewu = stop2
Kawalu= stop3 
roadtrip = gmaps.directions_layer(Sibolga, Sibolga, 
                                  waypoints=[Padang, Pringsewu, Kawalu],
                                  travel_mode="DRIVING")


In [40]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, 
                          vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

City_ID       City Country  Max Temp Current Description     Lat       Lng  \
0      455    Sibolga      ID     85.06     overcast clouds  1.7427   98.7792   
1      172     Padang      ID     86.05     overcast clouds -0.9492  100.3543   
2      574  Pringsewu      ID     84.96     overcast clouds -5.3582  104.9744   
3      585     Kawalu      ID     81.14       broken clouds -7.3817  108.2082   

                    Hotel Name  
0  Hotel Syariah CN Darussalam  
1               Mercure Padang  
2     Urban Style by Front One  
3             KOSAN UNGU UNSIK

In [41]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>

"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [44]:
# 11a. Add a marker layer for each city to the map.
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(roadtrip)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [45]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]


# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]